/**
 * Canonical notification vocabulary shared by every delivery channel.
 *
 * Keep these values stable: they are persisted, sent over sockets, and used
 * by mobile/web deep-link routers.
 */
const NOTIFICATION_TYPES = Object.freeze({
  DIRECT_MESSAGE: 'direct_message',
  FRIEND_REQUEST: 'friend_request',
  FRIEND_REQUEST_ACCEPTED: 'friend_request_accepted',
  ROOM_INVITE: 'room_invite',
  ROOM_JOINED: 'room_joined',
  ROOM_LEFT: 'room_left',
  ROOM_UPDATED: 'room_updated',
  ROOM_TASK_CREATED: 'room_task_created',
  ROOM_TASK_ASSIGNED: 'room_task_assigned',
  TASK_COMPLETED: 'task_completed',
  TASK_PROOF_SUBMITTED: 'task_proof_submitted',
  TASK_APPROVED: 'task_approved',
  REACTION_RECEIVED: 'reaction_received',
  APPRECIATION_RECEIVED: 'appreciation_received',
  NUDGE_RECEIVED: 'nudge_received',
  ACHIEVEMENT_UNLOCKED: 'achievement_unlocked',
  STREAK_RISK: 'streak_risk',
  TASK_REMINDER: 'task_reminder',
  SYSTEM: 'system',
});

const NOTIFICATION_PRIORITIES = Object.freeze({
  LOW: 'low',
  NORMAL: 'normal',
  HIGH: 'high',
});

const NOTIFICATION_CATEGORIES = Object.freeze({
  MESSAGES: 'messages',
  SOCIAL: 'social',
  ROOMS: 'rooms',
  TASKS: 'tasks',
  ACHIEVEMENTS: 'achievements',
  SYSTEM: 'system',
});

const TYPE_METADATA = Object.freeze({
  [NOTIFICATION_TYPES.DIRECT_MESSAGE]: { category: NOTIFICATION_CATEGORIES.MESSAGES, priority: NOTIFICATION_PRIORITIES.HIGH },
  [NOTIFICATION_TYPES.FRIEND_REQUEST]: { category: NOTIFICATION_CATEGORIES.SOCIAL, priority: NOTIFICATION_PRIORITIES.HIGH },
  [NOTIFICATION_TYPES.FRIEND_REQUEST_ACCEPTED]: { category: NOTIFICATION_CATEGORIES.SOCIAL, priority: NOTIFICATION_PRIORITIES.NORMAL },
  [NOTIFICATION_TYPES.ROOM_INVITE]: { category: NOTIFICATION_CATEGORIES.ROOMS, priority: NOTIFICATION_PRIORITIES.HIGH },
  [NOTIFICATION_TYPES.ROOM_JOINED]: { category: NOTIFICATION_CATEGORIES.ROOMS, priority: NOTIFICATION_PRIORITIES.NORMAL },
  [NOTIFICATION_TYPES.ROOM_LEFT]: { category: NOTIFICATION_CATEGORIES.ROOMS, priority: NOTIFICATION_PRIORITIES.NORMAL },
  [NOTIFICATION_TYPES.ROOM_UPDATED]: { category: NOTIFICATION_CATEGORIES.ROOMS, priority: NOTIFICATION_PRIORITIES.NORMAL },
  [NOTIFICATION_TYPES.ROOM_TASK_CREATED]: { category: NOTIFICATION_CATEGORIES.TASKS, priority: NOTIFICATION_PRIORITIES.NORMAL },
  [NOTIFICATION_TYPES.ROOM_TASK_ASSIGNED]: { category: NOTIFICATION_CATEGORIES.TASKS, priority: NOTIFICATION_PRIORITIES.HIGH },
  [NOTIFICATION_TYPES.TASK_COMPLETED]: { category: NOTIFICATION_CATEGORIES.TASKS, priority: NOTIFICATION_PRIORITIES.NORMAL },
  [NOTIFICATION_TYPES.TASK_PROOF_SUBMITTED]: { category: NOTIFICATION_CATEGORIES.TASKS, priority: NOTIFICATION_PRIORITIES.NORMAL },
  [NOTIFICATION_TYPES.TASK_APPROVED]: { category: NOTIFICATION_CATEGORIES.TASKS, priority: NOTIFICATION_PRIORITIES.HIGH },
  [NOTIFICATION_TYPES.REACTION_RECEIVED]: { category: NOTIFICATION_CATEGORIES.SOCIAL, priority: NOTIFICATION_PRIORITIES.LOW },
  [NOTIFICATION_TYPES.APPRECIATION_RECEIVED]: { category: NOTIFICATION_CATEGORIES.SOCIAL, priority: NOTIFICATION_PRIORITIES.NORMAL },
  [NOTIFICATION_TYPES.NUDGE_RECEIVED]: { category: NOTIFICATION_CATEGORIES.ROOMS, priority: NOTIFICATION_PRIORITIES.NORMAL },
  [NOTIFICATION_TYPES.ACHIEVEMENT_UNLOCKED]: { category: NOTIFICATION_CATEGORIES.ACHIEVEMENTS, priority: NOTIFICATION_PRIORITIES.NORMAL },
  [NOTIFICATION_TYPES.STREAK_RISK]: { category: NOTIFICATION_CATEGORIES.TASKS, priority: NOTIFICATION_PRIORITIES.HIGH },
  [NOTIFICATION_TYPES.TASK_REMINDER]: { category: NOTIFICATION_CATEGORIES.TASKS, priority: NOTIFICATION_PRIORITIES.NORMAL },
  [NOTIFICATION_TYPES.SYSTEM]: { category: NOTIFICATION_CATEGORIES.SYSTEM, priority: NOTIFICATION_PRIORITIES.NORMAL },
});

function getNotificationMetadata(type) {
  return TYPE_METADATA[type] || TYPE_METADATA[NOTIFICATION_TYPES.SYSTEM];
}

function buildNotificationDedupeKey({ type, recipientId, entityId, occurrence }) {
  return [type, recipientId, entityId || 'global', occurrence || 'event'].join(':');
}

module.exports = {
  NOTIFICATION_TYPES,
  NOTIFICATION_PRIORITIES,
  NOTIFICATION_CATEGORIES,
  getNotificationMetadata,
  buildNotificationDedupeKey,
};
